version: '2.1'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: bash -c " java -jar target/app.jar"
    networks:
      - app-mysql
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_dev_db
    ports:
      - "3306:3306"
    networks:
      - app-mysql
    volumes:
      - $HOME/Desktop/MySQL/linkdin.sql:/linkdin.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  app-mysql:
