-- MySQL Script generated by MySQL Workbench
-- Tue 10 Jul 2018 02:03:27 AM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema web_dev_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_dev_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_dev_db` DEFAULT CHARACTER SET utf8 ;
USE `web_dev_db` ;

-- -----------------------------------------------------
-- Table `web_dev_db`.`user_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dev_db`.`user_network` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_dev_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dev_db`.`user` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `profile_picture` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `profession` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `is_admin` TINYINT(1) NULL,
  `user_network_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_network_id`),
  INDEX `fk_user_user_network1_idx` (`user_network_id` ASC),
  CONSTRAINT `fk_user_user_network1`
    FOREIGN KEY (`user_network_id`)
    REFERENCES `web_dev_db`.`user_network` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `web_dev_db`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dev_db`.`post` (
  `id` INT NOT NULL,
  `content` TINYTEXT NULL,
  `timestamp` TIMESTAMP(1) NULL,
  `is_advertisment` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_post_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `web_dev_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_dev_db`.`post_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_dev_db`.`post_comment` (
  `id` INT NOT NULL,
  `content` TINYTEXT NULL,
  `comment_timestamp` TIMESTAMP(1) NULL,
  `post_id` INT NOT NULL,
  `post_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `post_id`, `post_user_id`),
  INDEX `fk_PostComment_post1_idx` (`post_id` ASC, `post_user_id` ASC),
  CONSTRAINT `fk_PostComment_post1`
    FOREIGN KEY (`post_id` , `post_user_id`)
    REFERENCES `web_dev_db`.`post` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
